相談会申し込み
shoko218/STECH_BOT pull request #13
Opened 2021-04-02 21:06 UTC by shoko218

相談会を申し込むとメンターチャンネルに申し込み内容が送信される機能を実装しました。

2021-04-11 12:37 UTC, nr0112 requested changes
実装お疲れさまでした☕️
2点気になったのでご確認ください🙇‍♀️

2021-04-11 12:37 UTC, nr0112 commented on app/Http/Controllers/SlashCommand/ShowApplyCounselingModalController.php
> +class ShowApplyCounselingModalController extends Controller
このクラス、コントローラの意義ってありますか？
中身はCounselingControllerでモーダルを表示するメソッドに飛ばしているだけなので、こちらではなく直接そのメソッドにルーティングしたらどうかな？と思ってしまいました。
あるいはクラスの命名から意味を読み取りづらいので、命名を変えるか、Docコメントを記述したほうがいいかもしれないです。

2021-04-11 12:37 UTC, nr0112 commented on app/Http/Controllers/CounselingController.php
> +        $menter_slack_id = $payload['view']['state']['values']['menter_slack_id']['menter_slack_id']['selected_option']['value'];
全体的にメンターの綴り間違ってます！mentorです...😭

2021-04-12 09:20 UTC, shoko218 commented on app/Http/Controllers/SlashCommand/ShowApplyCounselingModalController.php
> +class ShowApplyCounselingModalController extends Controller
ご指摘ありがとうございます。本当にその通りです。
#4 の機能を作っている時に、スラッシュコマンドで呼び出す機能をここに記述していたのですが、
イベント関連の機能をEventControllerにまとめた際にリファクタリングできておらず、
このファイルを残してしまっています。
その名残でこちらにも不要なファイルを作ってしまっているという次第です。
#4 の方もこちらの方も修正します。
ありがとうございます！

2021-04-12 09:21 UTC, shoko218 commented on app/Http/Controllers/CounselingController.php
> +        $menter_slack_id = $payload['view']['state']['values']['menter_slack_id']['menter_slack_id']['selected_option']['value'];
ご指摘ありがとうございます。
初歩的なミスで本当申し訳ないです…

2021-05-22 14:56 UTC, nr0112 approved these changes

2021-05-22 15:10 UTC, merged