機能仮完成(細かいところはまだできていない)
shoko218/STECH_BOT pull request #8
Opened 2021-03-05 11:44 UTC by shoko218

まだできていないところ
・入力値のバリデーション
・参加者表示の挙動修正

2021-03-14 09:45 UTC, shoko218 commented
### 参加者表示の挙動修正について


**確認していた挙動の不具合**
- 参加登録ボタンを押しても何も表示されない
- 参加登録ボタンを押した際に、自分の名前だけでなく自分以外のメンバーの名前も表示される

**対処**
挙動がおかしくなるタイミングを調べたところ、お知らせが投稿された後、最初に参加登録ボタンを押した時のみだった
加えて、挙動がおかしくなる投稿は時間操作で二度以上メッセージを送信しているものだった
上記2点より、同じイベントに対して別の投稿から参加登録したために表示上は登録できていないがDB上には登録しているという、開発中だからこそ起こるバグだと判断　
通常利用時は複数回投稿することを想定していないため、現状の仕様上では変更する必要がないと判断し、変更はしていない

2021-03-22 08:44 UTC, nr0112 commented
全体で気になった点と提案
- DocCommentの使用
今後開発メンバー増える可能性を考慮すると、メソッドの説明は書いておいたほうがいいと思います。
特に懸念点・改善の余地はコメントアウト複数行よりtodoで書く方がいいかも。
https://qiita.com/itosho/items/0f809e067a9e4a41515e
https://zonuexe.github.io/phpDocumentor2-ja/references/phpdoc/basic-syntax.html#doc

- composer.json、composer.lockはコミットすべきかどうか？
私のファイルと結構差分があるので、今後パッケージの依存関係が競合しないかな？と思いました。
今回の場合、私は初期のファイルからlaravel-slack-apiの削除とslack-php-apiの追加しかしておらず、コミットもしてないので、せぐが先にdevelopにマージすれば競合はしないかと思います。ですが今後は機能に関するファイルだけをマージしてから、developブランチでパッケージ更新&追加、それをコミットする方が安全かも。(定石がわからない..)
https://qiita.com/tanakahisateru/items/ff4118ffd6a404bceb64
https://getcomposer.org/doc/articles/resolving-merge-conflicts.md

2021-03-22 09:50 UTC, nr0112 requested changes
大変な機能を担当してくれて本当にありがとう🙇‍♀️

2021-03-22 09:50 UTC, nr0112 commented on app/Http/Controllers/InteractiveEndpointController.php
> +            if($postData['type'] === "view_submission"){//モーダルのフォームが送信された場合
typeで分けるのはすごくいいと思います！ありがとう！！
私が担当したミーティング機能も一度このInteractiveEndpointControllerを通して分岐・処理されるってことですよね？

だとしたら今の状態だとイベント登録関連の処理とごちゃ混ぜになってしまうので以下のようにファイル分けた方がいいと思います。どうでしょう...？
- 全てのアクションを受け取りtypeで行き先を分岐するInteractiveEndpointController
- ミーティングに関する処理を担当するMeetingController(作成済み)
- イベントに関する処理を担当するEventController

2021-03-22 09:50 UTC, nr0112 commented on app/Http/Controllers/InteractiveEndpointController.php
> +            $postData = json_decode($payload, true);
この変数名だけキャメルケースなのは何かルールがありますか？

2021-03-22 09:50 UTC, nr0112 commented on app/Http/Controllers/SlashCommand/ShowCreateEventModalController.php
> +                                ],
完全に思いつきなのですが、、時間の配列作成はforで0~23を回して作成できないのでしょうか？
````
$hours_array = array();
for ($i=0; $i<24; $i++) {
  $hours_array[] = ["text" => ["type" => "plain_text", "text" => "$i 時"], "value" => "$i"];
}

...
"options" => [$hours_array]
...
````
連想配列の追加になるから弾かれる...？

2021-03-23 09:13 UTC, shoko218 commented on app/Console/Commands/RemindEvent.php
> +    protected $description = 'Command description';
完全に忘れてました。ありがとうございます！

2021-03-23 09:14 UTC, shoko218 commented on app/Http/Controllers/InteractiveEndpointController.php
> +            $postData = json_decode($payload, true);
ミスです。変数名を変えました。ありがとうございます！

2021-03-23 09:18 UTC, shoko218 commented on app/Http/Controllers/InteractiveEndpointController.php
> +            if($postData['type'] === "view_submission"){//モーダルのフォームが送信された場合
提案ありがとうございます。
絶対にその方がいいと思うので変更しました。
イベントに関する処理を担当するEventControllerと
参加者に関する処理を担当するEventParticipantControllerをApp/Http/Controllers下に新規作成し、
InteractiveEndpointController内とApp/Console/Commands下に作成しているコマンドの中身を各ファイルに移しました。
ありがとうございます！

2021-03-23 09:20 UTC, shoko218 commented on app/Http/Controllers/SlashCommand/ShowCreateEventModalController.php
> +                                ],
提案ありがとうございます！
試してみたところ動かなくなってしまったので、連想配列の一部として連想配列を代入するということはできないようです。

2021-04-11 12:44 UTC, nr0112 requested changes

2021-04-11 12:44 UTC, nr0112 commented on app/Http/Controllers/InteractiveEndpointController.php
> +                switch ($payload['actions'][0]['action_id']) {
追記：
自分のほうでInteractiveEndpointControllerを作成して気付いたのですが、ここはactions_idではなくblock_idで識別する方が適切ではないでしょうか？action_idだとブロック内のコンポーネント一つ一つに割り振られているので、ブロック内にボタンなどのInteractive Componentsが複数ある場合はちょっと厳しいです。
#12 を参照していただければと思います。

2021-04-12 09:48 UTC, shoko218 commented on app/Http/Controllers/InteractiveEndpointController.php
> +                switch ($payload['actions'][0]['action_id']) {
ご指摘ありがとうございます。そちらの方が適切だと思います。
このコードを書いていた時、slack apiについての知識が足りておらず、
このような不適切な書き方をし、そのまま残し続けてしまっていたのだと思います。
勉強不足で申し訳ないです…

2021-04-21 15:43 UTC, kudotakuya reviewed
大きな部分コメントしました。
細かいロジックとかまでは見てないので、ここ見てほしいとかあれば言ってください。

2021-04-21 15:43 UTC, kudotakuya commented on app/Http/Controllers/EventController.php
> +            $this->slack_client->chatPostMessage([
commitしてから通知したほうがいいです

2021-04-22 09:46 UTC, shoko218 commented on app/Console/Commands/NoticeEvent.php
> +    protected $signature = 'command:notice_event';
ご指摘ありがとうございます！
event:でグループ化するようにします！

2021-04-22 16:55 UTC, shoko218 commented on app/Http/Controllers/EventController.php
> +    public function getModalConstitution()
ご指摘ありがとうございます！
確かに今EventControllerの半分がjsonで見づらかったです…
BlockPayloadsというディレクトリを作ってその下のファイルにjsonをまとめるようにしました！

2021-04-22 16:57 UTC, shoko218 commented on app/Http/Controllers/EventController.php
> +            $this->slack_client->chatPostMessage([
ご指摘ありがとうございます！
commit後に通知するように変更しました！

2021-05-22 12:07 UTC, nr0112 approved these changes

2021-05-22 12:09 UTC, merged